# Generated by Django 5.0.6 on 2024-06-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Boards',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, null=True)),
                ('task_description', models.TextField(null=True)),
                ('task_is_complete', models.BooleanField(default=False)),
                ('task_due_date', models.DateField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mytodoapp.board')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
