# Generated by Django 5.0.6 on 2024-06-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
